#!/usr/bin/env ruby

# The shortest password satisfying a policy, using Z3's native regexes.
#
# Z3 regexes are not Ruby Regexps and nothing converts between the two - they're
# built out of the combinators on Z3::Re. Matching is anchored, so "contains this
# somewhere" is spelled out as Re.Full + re + Re.Full.

require_relative "../lib/z3"

Re = Z3::Re

LOWER = Re.Range("a", "z")
UPPER = Re.Range("A", "Z")
DIGIT = Re.Range("0", "9")
PUNCT = Re.Union(*"!@#$%^&*".chars.map { |c| Re.Of(c) })

def anywhere(re)
  Re.Full + re + Re.Full
end

password = Z3.String("password")

optimize = Z3::Optimize.new
optimize.assert password.matches?(anywhere(LOWER))
optimize.assert password.matches?(anywhere(UPPER))
optimize.assert password.matches?(anywhere(DIGIT))
optimize.assert password.matches?(anywhere(PUNCT))
# Every character has to be one of the four classes - no spaces, no control codes
optimize.assert password.matches?((LOWER | UPPER | DIGIT | PUNCT).star)
# ...and the one thing everybody tries first
optimize.assert ~password.matches?(anywhere(Re.Of("password")))
optimize.assert password.length >= 8
optimize.minimize password.length

if optimize.satisfiable?
  puts optimize.model[password].value
else
  puts "No password satisfies this policy"
end
