#!/usr/bin/env ruby


require "pathname"
require_relative "../lib/z3"

class SudokuSolver
  def initialize(path)
    data = Pathname(path).read
    data = data.strip.split("\n").map do |line|
      line.split.map{|c| c == "_" ? nil : c.to_i}
    end
    @data = data
    @solver = Z3::Solver.new
  end

  def solve!
    @cells = (0..8).map do |j|
      (0..8).map do |i|
        cell_var(@data[j][i], i, j)
      end
    end

    @cells.each do |row|
      @solver.assert Z3.Distinct(*row)
    end
    @cells.transpose.each do |column|
      @solver.assert Z3.Distinct(*column)
    end
    @cells.each_slice(3) do |rows|
      rows.transpose.each_slice(3) do |square|
        @solver.assert Z3.Distinct(*square.flatten)
      end
    end

    if @solver.check == :sat
      @model = @solver.model
      print_answer!
    else
      puts "failed to solve"
    end
  end

  private

  def cell_var(cell, i, j)
    v = Z3.Int("cell[#{i+1},#{j+1}]")
    @solver.assert v >= 1
    @solver.assert v <= 9
    @solver.assert v == cell if cell != nil
    v
  end

  def print_answer!
    @cells.each do |row|
      puts row.map{|v| @model[v]}.join(" ")
    end
  end
end

path = ARGV[0] || Pathname(__dir__) + "sudoku-1.txt"
SudokuSolver.new(path).solve!
