#!/usr/bin/env ruby

# https://en.wikipedia.org/wiki/Zebra_Puzzle

require_relative "../lib/z3"

class ZebraPuzzle
  TRAITS = {
    color: [:red, :yellow, :green, :blue, :ivory],
    nationality: [:Englishman, :Spaniard, :Norwegian, :Ukrainian, :Japanese],
    drink: [:water, :coffee, :tea, :milk, :"orange juice"],
    cigarettes: [:Parliaments, :"Old Gold", :"Lucky Strike", :Kools, :Chesterfields],
    pet: [:zebra, :dog, :snails, :fox, :horse],
  }

  def initialize
    @solver = Z3::Solver.new
    @sorts = TRAITS.to_h{|trait, values| [trait, Z3::EnumSort.new(trait, values)] }
  end

  def traits
    TRAITS.keys
  end

  # House I has TRAIT value X
  def variable(trait, i)
    @sorts[trait].var("#{trait}-#{i}")
  end

  # Five houses and five values, so all different means every value gets used once
  def setup_variables(trait)
    @solver.assert Z3.Distinct(*(0..4).map{|i| variable(trait, i) })
  end

  def house_has_trait_value(i, trait, value)
    (variable(trait, i) == value)
  end

  def same_house(t1,v1,t2,v2)
    (0..4).each do |i|
      @solver.assert house_has_trait_value(i,t1,v1) == house_has_trait_value(i,t2,v2)
    end
  end

  def left_rigth_house(t1,v1,t2,v2)
    (0..3).each do |i|
      @solver.assert house_has_trait_value(i,t1,v1) == house_has_trait_value(i+1,t2,v2)
    end
  end

  def next_house(t1,v1,t2,v2)
    (0..4).each do |i|
      opts = [i+1,i-1].grep(0..4).map{|j| house_has_trait_value(i,t1,v1) == house_has_trait_value(j,t2,v2) }
      @solver.assert Z3.Or(*opts)
    end
  end

  def call
    traits.each do |trait|
      setup_variables(trait)
    end

    same_house(:nationality, :Englishman, :color, :red)
    same_house(:nationality, :Spaniard, :pet, :dog)
    same_house(:drink, :coffee, :color, :green)
    same_house(:nationality, :Ukrainian, :drink, :tea)
    same_house(:pet, :snails, :cigarettes, :"Old Gold")
    same_house(:cigarettes, :Kools, :color, :yellow)
    same_house(:cigarettes, :"Lucky Strike", :drink, :"orange juice")
    same_house(:nationality, :Japanese, :cigarettes, :Parliaments)

    next_house(:nationality, :Norwegian, :color, :blue)
    next_house(:cigarettes, :Chesterfields, :pet, :fox)
    next_house(:cigarettes, :Kools, :pet, :horse)

    left_rigth_house(:color, :ivory, :color, :green)

    @solver.assert house_has_trait_value(2, :drink, :milk)
    @solver.assert house_has_trait_value(0, :nationality, :Norwegian)

    if @solver.satisfiable?
      print_solution
    else
      puts "No solution"
    end
  end

  def print_solution
    model = @solver.model
    (0..4).each do |i|
      print "House #{i}:"
      traits.each do |trait|
        print " #{model[variable(trait, i)].value}"
      end
      print "\n"
    end
  end
end

ZebraPuzzle.new.call

__END__

There are five houses.
The Englishman lives in the red house.
The Spaniard owns the dog.
Coffee is drunk in the green house.
The Ukrainian drinks tea.
The green house is immediately to the right of the ivory house.
The Old Gold smoker owns snails.
Kools are smoked in the yellow house.
Milk is drunk in the middle house.
The Norwegian lives in the first house.
The man who smokes Chesterfields lives in the house next to the man with the fox.
Kools are smoked in the house next to the house where the horse is kept.
The Lucky Strike smoker drinks orange juice.
The Japanese smokes Parliaments.
The Norwegian lives next to the blue house.
Now, who drinks water? Who owns the zebra?
